name: ML Pipeline (Validate → Deploy)

on:
  push:
    branches:
      - "*"

jobs:

  # VALIDATE
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install mlflow tensorflow pandas numpy dvc

      - name: Pull Data
        run: |
          dvc pull || echo "Skipping DVC"

      - name: Train Model
        run: python train.py

      # DEBUG (optional but useful)
      - name: Show Files
        run: ls -la

      # Upload model_info.txt
      - name: Upload Model Info
        uses: actions/upload-artifact@v4
        with:
          name: model-info
          path: model_info.txt

      # Upload MLflow data
      - name: Upload MLflow Data
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-data
          path: mlruns/


  # DEPLOY
  deploy:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Download run_id
      - name: Download Model Info
        uses: actions/download-artifact@v4
        with:
          name: model-info

      # Download MLflow data
      - name: Download MLflow Data
        uses: actions/download-artifact@v4
        with:
          name: mlruns-data

      - name: Install MLflow
        run: pip install mlflow

      - name: Check Accuracy Threshold
        run: python check_threshold.py

      - name: Mock Docker Build
        run: |
          echo "Building Docker image for Run ID: $(cat model_info.txt)"
